// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rx_job_webapi.Services;

namespace rx_job_webapi.Migrations
{
    [DbContext(typeof(RxJobDbContext))]
    [Migration("20181028111816_InitialCreateDemoDb")]
    partial class InitialCreateDemoDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rx_job_webapi.Models.RX_Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractorID");

                    b.Property<DateTime>("DateCompleted");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateDelayed");

                    b.Property<string>("DelayReason");

                    b.Property<int>("Floor");

                    b.Property<string>("Name");

                    b.Property<int>("RJobID");

                    b.Property<int>("Room");

                    b.Property<string>("RoomType1");

                    b.Property<string>("Status");

                    b.Property<int>("StatusNum");

                    b.HasKey("JobID");

                    b.HasIndex("RoomType1");

                    b.ToTable("RxJobTbl");
                });

            modelBuilder.Entity("rx_job_webapi.Models.RX_RoomType", b =>
                {
                    b.Property<string>("RoomType")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.HasKey("RoomType");

                    b.ToTable("RxRoomTypeTbl");
                });

            modelBuilder.Entity("rx_job_webapi.Models.RX_Job", b =>
                {
                    b.HasOne("rx_job_webapi.Models.RX_RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomType1");
                });
#pragma warning restore 612, 618
        }
    }
}
